version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Europe/Belfast
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Aedius
  ignore:
  - dependency-name: futures-io
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: eventstore
    versions:
    - 0.9.6
