language: rust
rust:
  - stable
  - beta
  - nightly

env:
  - MOD_AUTH_SECRET=travis-secret-123

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
script:
  - cargo build
  - cargo test