apiVersion: v1
kind: Service
metadata:
  namespace: public
  name: service_auth
  labels:
    app: service_auth
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
spec:
  type: NodePort
  selector:
    app: service_auth
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
  ports:
    - name: http
      protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_auth
  namespace: public
  labels:
    app: service_auth
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_auth
      chart: {{ .Chart.Name | quote }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: service_auth
        chart: {{ .Chart.Name | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: service_auth
          image: "{{ (index .Values.images "service_auth").repository }}:{{ (index .Values.images "service_auth").tag }}"
          ports:
            - containerPort: 8100
      imagePullSecrets:
        - name: github-docker-login
