name: Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker login
        run: docker login docker.pkg.github.com -u Aedius -p ${{ secrets.package_token }}
      - name: Build the Docker image
        run: docker build --file Dockerfile --build-arg MOD_AUTH_SECRET_DEFAULT="${{ secrets.MOD_AUTH_SECRET }}" --tag docker.pkg.github.com/horfimbor/service_auth/service_auth:$GITHUB_SHA .
      - name: docker push
        run: docker push docker.pkg.github.com/horfimbor/service_auth/service_auth:$GITHUB_SHA

