name: Docker Image

on:
  push:
    branches:
      - master
      - test_build

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build  --file Dockerfile --build-arg MOD_AUTH_SECRET_DEFAULT=${{ secrets.MOD_TOKEN_SECRET }} --tag service_auth:$(date +%s) .